import puppeteer from "puppeteer-core";
const URL = process.env.URL ?? "http://localhost:5246/";
const b = await puppeteer.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: "new" });
const ok = (c, m) => console.log(c ? "OK  " : "FALHA", m);
const espera = (ms) => new Promise((r) => setTimeout(r, ms));
let p = await b.newPage();
const erros = [];
p.on("pageerror", (e) => erros.push(e.message));
p.on("console", (m) => m.type() === "error" && erros.push(m.text()));
await p.setViewport({ width: 1280, height: 900 });
await p.goto(URL, { waitUntil: "networkidle2", timeout: 120000 });
await p.evaluate(() => { window.__abriu = []; window.open = (u) => { window.__abriu.push(u); return null; }; });
await p.$eval("#contato", (e) => e.scrollIntoView());
await p.click("#contato button[type=submit]");
await espera(2500);
const msgs = await p.$$eval("#contato [id$=-erro]", (els) => els.map((e) => e.textContent));
ok(msgs.length === 3, `erros específicos: ${msgs.join(" | ")}`);
ok((await p.$$eval("#contato [aria-invalid=true]", (e) => e.length)) === 3, "aria-invalid nos 3 campos");
await p.type("#orc-nome", "Maria Teste");
await p.type("#orc-whatsapp", "24999887766");
ok((await p.$eval("#orc-whatsapp", (e) => e.value)) === "(24) 99988-7766", "máscara do WhatsApp");
await p.select("#orc-ambiente", "Cozinha planejada");
await p.click("#contato button[type=submit]");
await espera(3000);
const sucesso = await p.$eval("#contato [role=status]", (e) => e.textContent).catch(() => null);
ok(sucesso?.includes("Pedido recebido"), "sucesso substitui o formulário");
const wa = await p.evaluate(() => window.__abriu[0] ?? null);
console.log("     whatsapp aberto:", wa ? decodeURIComponent(wa).slice(0, 120) : "nenhum (modo servidor)");
await p.$eval("#portfolio", (e) => e.scrollIntoView());
await p.click("#portfolio button[aria-pressed=false]");
await espera(500);
const filtrados = await p.$$eval("#portfolio ul button[aria-label^=Ampliar]", (e) => e.length);
ok(filtrados > 0 && filtrados < 20, `filtro reduz a grade (${filtrados})`);
await p.$eval("#portfolio ul button[aria-label^=Ampliar]", (e) => e.click());
await espera(1500);
ok(await p.evaluate(() => document.querySelector("dialog.galeria")?.open), "lightbox abre");
const a = await p.$eval("dialog.galeria [aria-live]", (e) => e.textContent);
await p.keyboard.press("ArrowRight"); await espera(300);
const c = await p.$eval("dialog.galeria [aria-live]", (e) => e.textContent);
ok(a !== c, `seta navega (${a.slice(0, 6)} -> ${c.slice(0, 6)})`);
await p.keyboard.press("Escape"); await espera(400);
ok(!(await p.$("dialog.galeria")) && (await p.evaluate(() => document.activeElement?.getAttribute("aria-label")?.startsWith("Ampliar"))), "Esc fecha e devolve o foco");
ok(!/5,0 no Google/.test(await p.evaluate(() => document.body.innerText)), "nenhum 5,0 no Google");
ok(erros.length === 0, `console sem erros ${erros.join(" | ")}`);
await p.close();
p = await b.newPage();
await p.setViewport({ width: 375, height: 812, isMobile: true });
await p.goto(URL, { waitUntil: "networkidle2", timeout: 120000 });
await p.click("button[aria-controls=menu-celular]"); await espera(300);
ok(await p.evaluate(() => getComputedStyle(document.getElementById("menu-celular")).display === "flex" && document.querySelector("main").inert), "menu do celular abre e trava o fundo");
await p.keyboard.press("Escape"); await espera(200);
ok(await p.evaluate(() => getComputedStyle(document.getElementById("menu-celular")).display === "none"), "Esc fecha o menu");
await b.close();
